name: dbp
channels:
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.13.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astroid=2.6.6
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - click=8.0.1
  - coverage=5.5
  - cython=0.29.24
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flake8=3.9.2
  - gast=0.2.2
  - google-pasta=0.2.0
  - grpcio=1.36.1
  - h5py=3.2.1
  - hdf5=1.10.6
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.2
  - lazy-object-proxy=1.6.0
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - mypy=0.910
  - mypy_extensions=0.4.3
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - packaging=21.0
  - pandas=1.3.1
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - protobuf=3.17.2
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.1
  - pygments=2.9.0
  - pylint=2.9.6
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.7.11
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - readline=8.1
  - regex=2021.4.4
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - biopython==1.79
    - joblib==1.0.1
    - pydot==1.4.2
    - scikit-learn==0.24.2
    - sklearn==0.0
    - threadpoolctl==2.2.0
