name: tf2.5
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cudatoolkit=11.2.2
  - cudnn=8.2.1.32
  - intel-openmp=2021.3.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - numexpr=2.7.3
  - openssl=1.1.1k
  - pandas=1.3.1
  - pip=21.0.1
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.13.0
    - astunparse==1.6.3
    - backcall==0.2.0
    - biopython==1.79
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - decorator==5.0.9
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.2
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - matplotlib-inline==0.1.2
    - numpy==1.18.4
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.10.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - threadpoolctl==2.2.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
